### ISSUE TITLE
Issue with latest Wordnet data?

### ISSUE THREAD

**Issue by rogerdickey** [zaibacu/thesaurus#4]
I just tried running this with a download of the latest Wordnet database and it seems to miss some data. Perhaps the format changed? The file I'm getting is ~5mb smaller and many entries have an empty array for synonyms, such as:

{"pos": "noun", "wordnet_id": "05843616", "word": "mother", "key": "mother_01", "synonyms": []}
{"pos": "noun", "wordnet_id": "10352098", "word": "mother", "key": "mother_02", "synonyms": ["female_parent"]}
{"pos": "noun", "wordnet_id": "10352574", "word": "mother", "key": "mother_01", "synonyms": []}
{"pos": "noun", "wordnet_id": "10352666", "word": "mother", "key": "mother_01", "synonyms": []}
{"pos": "noun", "wordnet_id": "15131241", "word": "mother", "key": "mother_01", "synonyms": []}
{"pos": "verb", "wordnet_id": "02556213", "word": "mother", "key": "mother_03", "synonyms": ["fuss"]}

vs these are the entries from your upload 6 years ago:

{"word": "mother", "key": "mother_2", "pos": "noun", "synonyms": ["female parent"]}
{"word": "mother", "key": "mother_6", "pos": "verb", "synonyms": ["bring fort", "father", "generate", "engender", "sire", "beget", "get"]}
{"word": "mother", "key": "mother_7", "pos": "verb", "synonyms": ["overprotect", "fuss"]}

Any chance you can update it, or any guidance for what I should do to fix? Thanks!

**Comment by zaibacu** [comment]
Hello, thank you for noticing the issue! I will look into it.

**Comment by zaibacu** [comment]
So in short - original file was extracted in quick way and the script was recreated later on. While checking I did notice few inconsistencies, should be fixed now. Also, added glossary as `desc` - looks like a useful field.

The size difference is mostly due to more lines in old file. Now every record is linked to proper wordnet ID, previously it was just unique word found in index, and there are more of these:

len(unique_words_in_index) = 155467
Lines in Old: 169009
Lines in New: 117791

So it looks like some of word were removed over the years from Wordnet itself, but mostly it was not correct parsing. 

I've added new version of file but still keep the old one if someone will find it useful.
